export const Categories = [
  "Fusillade solo ",
  "Fusillade duo",
  "Fusillade position",
  "Taxi",
  "Exercise de style",
  "Carré hollandais",
  "Carré anglais",
  "Char québecois",
  "Littéraire",
  "A la manière de",
  "Epistolaire",
  "Abécédaire",
  "Avec accents",
  "Carnage",
  "Mort en scène",
  "Rimée",
  "Animalière",
  "Assis, Debout, Couché",
  "Auditive",
  "Avec Accessoire",
  "Avec Exagération",
  "Ca Passe ou Ca Casse",
  "Chantée",
  "Comédie musicale",
  "Dégressive",
  "Dramatique",
  "Défi des équipes",
  "Oscar",
  "Doublage Américain",
  "Zapping relais",
  "Étages",
  "Diapositives",
  "Feuilleton",
  "Grosse Colère",
  "Maître & Valet",
  "On connait la fin",
  "Le pire de",
  "Point de vue",
  "Poursuite",
  "Double poursuite",
  "Proverbes à la c*n",
  "Roman Photo",
  "Toaster",
  "Tiens, ça me rappelle une chanson",
  "Travelling",
  "Video-Way",
  "Zones d'Humeur"
]
