export * from './projection/projection.component';
export * from './projection/scoreboard/scoreboard-team/scoreboard-team.component';
export * from './projection/scoreboard/scoreboard.component';
export * from './video-switcher/video-switcher.component';
export * from './page-not-found/page-not-found.component'
export * from './video-switcher/teams-parameters/teams-parameters.component'
export * from './video-switcher/match-manager/match-manager.component';
export * from './video-switcher/teams-parameters/team-form/team-form.component';
export * from './projection/team-presentation/team-presentation.component'
export * from './video-switcher/match-manager/team-manager-panel/team-manager-panel.component'
export * from './video-switcher/match-manager/impro-manager-panel/impro-manager-panel.component'
