export enum DisplayedScreen {
  SCREEN_SAVER = 'SCREEN_SAVER',
  MATCH = 'MATCH',
  TEAM_A = 'TEAM_A',
  TEAM_B = 'TEAM_B',
  STAR_PLAYER = 'STAR_PLAYER',
  VOTE = 'VOTE',
  ANTHEM = 'ANTHEM',
  MEDIA = 'MEDIA',
  PUBS = 'PUBS',
  PROJECTION_HANDLING_HELPER = 'PROJECTION_HANDLING_HELPER',
}
